services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - network
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:3000"
    depends_on:
      - database
    networks:
      - internal-network
      - network
    restart: unless-stopped

  database:
    container_name: database
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  internal-network:
    driver: bridge
  network:
    driver: bridge